Added commit ID checking

diff --git a/.github/workflows/prod.deployment.yaml b/.github/workflows/prod.deployment.yaml
--- a/.github/workflows/prod.deployment.yaml
+++ b/.github/workflows/prod.deployment.yaml
@@ -37,7 +37,7 @@ jobs:
                 echo "rc-commit-id=$(git log -1 --pretty=format:"%h")" >> $GITHUB_OUTPUT
 
     validate-commit-ids:
-        name: Run debug action
+        name: Match RC abd Production commit ID's
         runs-on: ubuntu-latest
         needs:
             - set-version-tags
@@ -47,8 +47,9 @@ jobs:
                   fetch-depth: 0
             - name: run workflow
               run: |
-                  echo $(git log -1 --pretty=format:"%h")
-                  echo ${{ needs.set-version-tags.outputs.rc-commit-id }}
+                  if ! [[ $(git log -1 --pretty=format:"%h") == ${{ needs.set-version-tags.outputs.rc-commit-id }} ]]; then
+                      echo "::error::Filename Commit ID $(git log -1 --pretty=format:"%h") does not match Release Candidate ${{ needs.set-version-tags.outputs.rc-commit-id }}" && exit 1
+                  fi
                   
     deploy-prod:
         name: Retag and Deploy to Production
