Check tags in jobs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,11 +3,18 @@ name: Publish to Production
 on:
   push:
     tags:
-      - '[0-9{1,3}].[0-9{1,3}].[0-9{1,3}]'
+      - '*'
       
 jobs:
-  deploy:
-    name: "Deploy application"
-    runs-on: ubuntu-24.04
+  validate-tag:
+    runs-on: ubuntu-latest
     steps:
-      - run: "echo ${{ github.ref_name }}"
+      - name: Check tag name
+        run: |
+          TAG_NAME="${GITHUB_REF#refs/tags/}"
+          if [[ ! "$TAG_NAME" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+            echo "❌ Invalid tag name: $TAG_NAME"
+            exit 1
+          else
+            echo "✅ Valid tag: $TAG_NAME"
+          fi
